### ISSUE TITLE
Definition of done

### ISSUE THREAD

**Issue by hubregtsejoost** [hubregtsejoost/your-tribe-squad-page#1]
- [x]  De squadpage staat op Github en heeft een live url

- [x]  Je hebt met een team een responsive squad page ontworpen en gemaakt

- [x]  Je hebt gewerkt volgens de verschillende fases van de development-lifecycle en je hebt het proces bijgehouden in jouw I Love Web - Learning Log

- [x]  Je hebt het team-canvas ingevuld en toegevoegd aan de issues van de repository waar jullie in samenwerken

- [x]  Je hebt verschillende schetsen gemaakt voor het responsive ontwerp en met een media-query verschillende layouts gemaakt en feedback gekregen in Github Issues

- [x]  Je hebt verschillende variaties geschetst voor de layout en de visuele hiërachie en feedback gekregen in Github Issues

 

- [x] Je hebt het ontwerp gerealiseerd met HTML, CSS en/of JS, je hebt code uitgelegd en feedback gekregen in Github Issues

**Comment by Haroub-S** [comment]
completed
