### ISSUE TITLE
plaatjes op klein scherm passend maken zodat er geen overflow is

### ISSUE THREAD

**Issue by shooft** [hubregtsejoost/your-tribe-squad-page#10]

**Comment by Haroub-S** [comment]
completed
https://hubregtsejoost.github.io/your-tribe-squad-page/Branco/index.html
https://hubregtsejoost.github.io/your-tribe-squad-page/Haroub/index.html
https://hubregtsejoost.github.io/your-tribe-squad-page/Joost/index.html
