### ISSUE TITLE
Header en Navbar is broken on your site (on tablet mode). can you fix it?

### ISSUE THREAD

**Issue by Haroub-S** [hubregtsejoost/your-tribe-squad-page#16]

**Comment by hubregtsejoost** [comment]
How do i replicate this? Tried testing it and seems to work properly.

**Comment by Haroub-S** [comment]
https://github.com/user-attachments/assets/85d616df-2cce-4350-b3d7-3cfa6ef18625

i have uploaded a video for you. when i open it on my tablet Lenovo Tab 12 it breaks.

**Comment by hubregtsejoost** [comment]
Komt door een overflow probleem van een animatie die ik in https://github.com/hubregtsejoost/your-tribe-squad-page/issues/19 heb beschreven.
