### ISSUE TITLE
Design schetsen

### ISSUE THREAD

**Issue by hubregtsejoost** [hubregtsejoost/your-tribe-squad-page#3]
Gemaakte design schetsen hier toevoegen.

**Comment by hubregtsejoost** [comment]
https://www.figma.com/design/w8QCrHoylOWm9rU0pkzHk9/Team-Canvas?m=auto&t=WSohGnLCss4T0w5W-6

**Comment by KoopReynders** [comment]
Per klus, of taak kun je een issue aanmaken waarin je schetsen, breakdown schets, ontwerpen in Figma, feedback en code verzameld. Als je een taak af hebt, sluit je het issue met een link naar de betreffende commit. Dat is gestructureerd werken ...

**Comment by hubregtsejoost** [comment]
https://www.figma.com/design/w8QCrHoylOWm9rU0pkzHk9/Team-Canvas?node-id=0-1&t=NNZzjSU33LWnDcYX-1
