### ISSUE TITLE
Read Me maken

### ISSUE THREAD

**Issue by Brancovanbeek** [hubregtsejoost/your-tribe-squad-page#8]
Read Me maken

-Bespreek met je team welke taken nog nodig (en haalbaar) zijn om jullie squad page af te ronden deze laatste dagen.

-Maak een issue aan per taak, en assign het teamlid dat deze taak nog op gaat pakken.

-Bekijk ook welke andere issues nog openstaan, en nog opgepakt of gesloten kunnen worden.

-Maak via edu.nl alvast een korte link aan voor jullie website, en voeg deze toe aan jullie Readme.

-Breid jullie Readme uit met een korte uitleg over jullie project, en beschrijf drie opvallende features, waar jullie trots op zijn.
Voeg wat screenshots toe aan de Readme; laat bijvoorbeeld zien hoe jullie project er op verschillende devices uitziet. Dit is jullie etalage.

-Schrijf in de Readme wat over jullie team; wie zijn de teamleden, en waar kun je meer informatie over jullie vinden?

-Vraag een docent of ander team om feedback op jullie Readme.

-Ga aan de slag met de nog openstaande issues.

**Comment by Haroub-S** [comment]
completed
